title: Brandon's Blog
author: Brandon Braun
email: brandon.braun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog by Brandon Braun on coding ideas

# social links
twitter_username: bmb330
github_username:  bmb330

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
